"""
config.py — central settings for the player prop model + impact page backend.

Everything downstream reads from here: file paths, API keys, model tuning
constants, and the market definitions that tie a prop type to the stat it
projects and the defensive unit that adjusts it.
"""
import os

# ---------------- SEASON / WEEK ----------------
SEASON = 2025  # backtest season; override per-run with build.py --season
# Weeks 1-3 lean on prior-year rates only (no current-season signal yet);
# week 4+ can blend in current-season game logs as they accumulate.
PRIOR_ONLY_UNTIL_WEEK = 3
# Blend weight for week 4+: current-season-to-date rate gets
# games_so_far / (games_so_far + this) of the weight, prior-year gets the
# rest -- same shrinkage-toward mechanism as SHRINKAGE_GAMES, applied to
# blending two real data sources instead of regressing toward a position
# mean. Kept as its own knob since the two are conceptually different.
CURRENT_SEASON_BLEND_GAMES = 4

# ---------------- API KEYS ----------------
# Set via .env (gitignored) -- see .env.example. No hardcoded fallback: fail
# loudly rather than silently run with a missing/stale key.
ODDS_API_KEY = os.environ.get("ODDS_API_KEY")
CFBD_API_KEY = os.environ.get("CFBD_API_KEY")

ODDS_SPORT  = "americanfootball_ncaaf"
ODDS_REGION = "us"
ODDS_FORMAT = "american"

# ---------------- FILE PATHS ----------------
# Repo layout is flat (everything lives at BASE_DIR, no data/ or
# impact_backend/ subfolders) -- match PROJECT_STATE.md / README.md to this.
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR    = os.path.join(BASE_DIR, "output")        # generated tables + json
PFF_CROSSWALK = os.path.join(BASE_DIR, "master_crosswalk.csv")
TEAM_MAP      = os.path.join(BASE_DIR, "team_map.csv")   # pff_team -> cfbd_team -> odds_team

# Prior-year stat inputs -- generated by build_player_tables.py from the
# per-market *_season_clean.csv / *_weekly_clean.csv files. Not committed
# (derived data); run `python3 build_player_tables.py` to (re)generate.
SEASON_TOTALS = os.path.join(BASE_DIR, "player_season_totals.csv")  # one row per player
GAME_LOGS     = os.path.join(BASE_DIR, "player_game_logs.csv")      # one row per player-game

# Real prior-year (2024) rates, keyed by player_id only (no team -- see
# build_player_tables.py on why: a transfer's 2024 team isn't their 2025
# team). Only exists if the 2024_*_season_clean.csv inputs were provided.
PRIOR_SEASON_TOTALS = os.path.join(BASE_DIR, "player_prior_totals.csv")

# ---------------- MARKET DEFINITIONS ----------------
# Each Odds API prop market maps to: the stat we project, the volume + efficiency
# columns it decomposes into, and which defensive grade adjusts it.
# def_unit is a column family in the PFF crosswalk (def_grade_cov, def_grade_rdef...).
MARKETS = {
    "player_pass_yds": dict(stat="pass_yds", volume="pass_att", eff="ypa",
                            def_unit="def_grade_cov",  side="pass"),
    "player_pass_attempts": dict(stat="pass_att", volume="pass_att", eff=None,
                            def_unit="def_grade_cov",  side="pass"),
    "player_rush_yds": dict(stat="rush_yds", volume="rush_att", eff="ypc",
                            def_unit="def_grade_rdef", side="rush"),
    "player_rush_attempts": dict(stat="rush_att", volume="rush_att", eff=None,
                            def_unit="def_grade_rdef", side="rush"),
    "player_reception_yds": dict(stat="rec_yds", volume="targets", eff="ypt",
                            def_unit="def_grade_cov",  side="pass"),
    "player_receptions": dict(stat="receptions", volume="targets", eff="catch_rate",
                            def_unit="def_grade_cov",  side="pass"),
}

# ---------------- MODEL TUNING ----------------
# Regression-to-mean weight: how hard to pull a player's efficiency toward the
# position average when their prior-year sample is small. Higher = more shrinkage.
SHRINKAGE_GAMES = 6      # a player with this many prior games is ~half-regressed

# Opponent adjustment strength: how much a 1-SD defensive grade moves a projection.
# 0.15 means an elite (worst) pass defense scales pass projections by ~±15% at 1 SD.
OPP_ADJ_STRENGTH = 0.15

# ---------------- GAME CONTEXT (this week's spread/total) ----------------
# Season-average rates don't know this week's specific matchup is expected
# to be a shootout or a blowout -- these two knobs let a game's implied
# team total / spread (from --game-lines historical pull, or build.py's
# live odds once wired) nudge expected volume. Both are no-ops (multiplier
# of 1.0) if no game-lines data is loaded, so this is fully opt-in.
PACE_CLIP = 0.3              # cap the pace multiplier at 1 +/- this
SPREAD_SCALE = 21.0          # spread (points) at which the script effect maxes out
SCRIPT_ADJ_STRENGTH = 0.15   # how much a maxed-out script effect shifts rush/pass volume

# Minimum prior-year volume to project a player at all (filters noise).
MIN_PRIOR_VOLUME = dict(pass_att=100, rush_att=30, targets=20)

# Edge thresholds for flagging (in the stat's own units).
EDGE_FLAG = dict(pass_yds=20, rush_yds=12, rec_yds=12,
                 pass_att=3, rush_att=3, receptions=1.0)
