"""
config.py — central settings for the player prop model + impact page backend.

Everything downstream reads from here: file paths, API keys, model tuning
constants, and the market definitions that tie a prop type to the stat it
projects and the defensive unit that adjusts it.
"""
import os

# ---------------- SEASON / WEEK ----------------
SEASON = 2025  # backtest season; override per-run with build.py --season
# Weeks 1-3 lean on prior-year rates only (no current-season signal yet);
# week 4+ can blend in current-season game logs as they accumulate.
PRIOR_ONLY_UNTIL_WEEK = 3
# Blend weight for week 4+: current-season-to-date rate gets
# games_so_far / (games_so_far + this) of the weight, prior-year gets the
# rest -- same shrinkage-toward mechanism as SHRINKAGE_GAMES, applied to
# blending two real data sources instead of regressing toward a position
# mean. Kept as its own knob since the two are conceptually different.
CURRENT_SEASON_BLEND_GAMES = 4

# ---------------- API KEYS ----------------
# Set via .env (gitignored) -- see .env.example. No hardcoded fallback: fail
# loudly rather than silently run with a missing/stale key.
ODDS_API_KEY = os.environ.get("ODDS_API_KEY")
CFBD_API_KEY = os.environ.get("CFBD_API_KEY")

ODDS_SPORT  = "americanfootball_ncaaf"
ODDS_REGION = "us"
ODDS_FORMAT = "american"

# ---------------- FILE PATHS ----------------
# Repo layout is flat (everything lives at BASE_DIR, no data/ or
# impact_backend/ subfolders) -- match PROJECT_STATE.md / README.md to this.
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR    = os.path.join(BASE_DIR, "output")        # generated tables + json
PFF_CROSSWALK = os.path.join(BASE_DIR, "master_crosswalk.csv")
TEAM_MAP      = os.path.join(BASE_DIR, "team_map.csv")   # cfbd_name -> odds_name
PFF_TEAM_MAP  = os.path.join(BASE_DIR, "pff_team_map.csv")  # pff_team -> cfbd_team (build_pff_team_map.py)
TEAM_RATINGS  = os.path.join(BASE_DIR, "team_ratings_2025.csv")  # CFBD-style rush/pass rate + success rate, offense/defense

# Prior-year stat inputs -- generated by build_player_tables.py from the
# per-market *_season_clean.csv / *_weekly_clean.csv files. Not committed
# (derived data); run `python3 build_player_tables.py` to (re)generate.
SEASON_TOTALS = os.path.join(BASE_DIR, "player_season_totals.csv")  # one row per player
GAME_LOGS     = os.path.join(BASE_DIR, "player_game_logs.csv")      # one row per player-game

# Real prior-year (2024) rates, keyed by player_id only (no team -- see
# build_player_tables.py on why: a transfer's 2024 team isn't their 2025
# team). Only exists if the 2024_*_season_clean.csv inputs were provided.
PRIOR_SEASON_TOTALS = os.path.join(BASE_DIR, "player_prior_totals.csv")

# Which file is "prior year" depends on which season is being projected --
# for 2025 (the backtest season) that's the real 2024 data above; for 2026
# (live) it's 2025's OWN season totals (SEASON_TOTALS) -- this season's
# finished totals become next season's prior-year input, same file, no
# separate build step needed since player_season_totals.csv already has
# the exact schema load_prior_totals() expects. load_prior_totals(season=)
# falls back to PRIOR_SEASON_TOTALS for any season not listed here.
PRIOR_TOTALS_BY_SEASON = {
    2025: PRIOR_SEASON_TOTALS,
    2026: SEASON_TOTALS,
}

# ---------------- MARKET DEFINITIONS ----------------
# Each Odds API prop market maps to: the stat we project, the volume + efficiency
# columns it decomposes into, and which defensive grade adjusts it.
# def_unit is a column family in the PFF crosswalk (def_grade_cov, def_grade_rdef...).
MARKETS = {
    "player_pass_yds": dict(stat="pass_yds", volume="pass_att", eff="ypa",
                            def_unit="def_grade_cov",  side="pass"),
    "player_pass_attempts": dict(stat="pass_att", volume="pass_att", eff=None,
                            def_unit="def_grade_cov",  side="pass"),
    "player_rush_yds": dict(stat="rush_yds", volume="rush_att", eff="ypc",
                            def_unit="def_grade_rdef", side="rush"),
    "player_rush_attempts": dict(stat="rush_att", volume="rush_att", eff=None,
                            def_unit="def_grade_rdef", side="rush"),
    "player_reception_yds": dict(stat="rec_yds", volume="targets", eff="ypt",
                            def_unit="def_grade_cov",  side="pass"),
    "player_receptions": dict(stat="receptions", volume="targets", eff="catch_rate",
                            def_unit="def_grade_cov",  side="pass"),
}

# ---------------- MODEL TUNING ----------------
# Regression-to-mean weight: how hard to pull a player's efficiency toward the
# position average when their prior-year sample is small. Higher = more shrinkage.
SHRINKAGE_GAMES = 6      # a player with this many prior games is ~half-regressed

# Opponent adjustment strength: how much a 1-SD defensive PFF grade moves a
# projection (0.15 means an elite pass defense scales pass projections by
# ~+-15% at 1 SD). Disabled (0.0): a week 1-15 backtest was the first time
# this was ever actually active (opp_tkey was always None in every prior
# backtest run), and once active it measurably HURT hit rate -- receptions
# dropped 57.0%->54.7% with it on. See SUCCESS_RATE_ADJ_STRENGTH below,
# a CFBD-derived opponent signal that helped every market instead.
OPP_ADJ_STRENGTH = 0.0

# ---------------- GAME CONTEXT (this week's spread/total) ----------------
# Season-average rates don't know this week's specific matchup is expected
# to be a shootout or a blowout -- these two knobs let a game's implied
# team total / spread (from --game-lines historical pull, or build.py's
# live odds once wired) nudge expected volume. Both are no-ops (multiplier
# of 1.0) if no game-lines data is loaded, so this is fully opt-in.
PACE_CLIP = 0.3              # cap the pace multiplier at 1 +/- this
SPREAD_SCALE = 21.0          # spread (points) at which the script effect maxes out
# Rush and pass need independent strengths, not one shared +/- knob: a
# week 1-15 sweep showed rush bias converges to ~0 around 0.75-0.85, while
# the SAME strength pushed the OTHER direction on pass/reception markets
# (their bias got worse, not better, as strength increased) -- so a single
# shared constant can't optimize both at once.
#
# IMPORTANT, from the same sweep: bias-to-actual and hit-rate-vs-the-book-
# line are NOT the same thing. rush_yds bias went from -0.4 to +1.1 (fully
# calibrated) across this whole range while its flagged-edge hit rate sat
# flat at ~50.2% throughout -- the book already prices in game script, so
# an unbiased model converges toward what the book already knew, not
# toward beating it. These values are chosen for accurate CALIBRATION
# (useful for the Impact page's raw projections), not because they were
# shown to improve betting hit rate -- they didn't, on this data.
RUSH_SCRIPT_STRENGTH = 0.80
PASS_SCRIPT_STRENGTH = 0.05

# CFBD-derived opponent adjustment, independent of the PFF-grade one
# above -- different data source (play-level EPA/success rate vs PFF's
# subjective grading), same role: how good is this opponent at stopping
# this side of the ball. Multiplies into the same adj slot as
# OPP_ADJ_STRENGTH rather than replacing it.
#
# A week 1-15 sweep found pass_yds and the receiving markets (reception_
# yds, receptions) respond in OPPOSITE directions to this knob, even
# though both are "side=pass" (targets are fed by the passing game) --
# pass_yds hit rate rose 51.6%->54.7% as strength went 0.10->0.50, while
# receptions fell 58.7%->56.3% over the same range. So it's keyed by
# stat, not just side; a stat missing from this dict falls back to
# SUCCESS_RATE_ADJ_STRENGTH.
SUCCESS_RATE_ADJ_STRENGTH = 0.15  # fallback for any stat not listed below
SUCCESS_RATE_STRENGTH_BY_STAT = dict(
    pass_yds=0.35, pass_att=0.35,      # rose with strength in the sweep
    rec_yds=0.10, receptions=0.10,     # fell with strength -- keep it low
    rush_att=0.10,                     # fell with strength -- keep it low
    rush_yds=0.15,                     # roughly flat -- default is fine
)

# Team-level PFF grade matchup adjustment (team_pff_grades_2025.csv) --
# replaces the old individual-player-aggregated PFF opponent grade
# (OPP_ADJ_STRENGTH, disabled above): this is PFF's own team-level grade,
# not our aggregation of it, and it's a MATCHUP (this team's own relevant
# unit vs the opponent's complementary one), not a single-sided opponent
# read. rush markets: offense run-BLOCKING vs defense run-DEFENSE.
#
# Tested applying the same matchup idea to pass (block vs pass-rush) and
# receiving (recv vs coverage) markets too -- rush-only outperformed:
# adding it to the other four markets measurably hurt them (e.g.
# receptions 58.7%->56.8%) while barely moving pass_yds, so it's rush-only
# here. A strength sweep on rush found a real tradeoff too: hit rate
# creeps up with strength (50.9%->52.3% from 0.15->0.50) but bias grows
# much faster (+5.7->+17.3 proj-actual) -- 0.15 is the better trade, not
# the best hit rate in isolation. Not yet backtested against a by-week
# version of this data (season-aggregate only, same lookahead caveat as
# team_ratings).
MATCHUP_UNITS = dict(
    player_rush_yds=("grade_rblk", "grade_rdef"),
    player_rush_attempts=("grade_rblk", "grade_rdef"),
)
MATCHUP_ADJ_STRENGTH = 0.15

# 2026-forward team-strength adjustment (team_ratings_2025.csv's OffAdj/
# DefAdj/rank_TARP columns -- this team's 2025 performance already
# adjusted for 2026 coaching changes + returning production, computed by
# the data source, not by us). Differential like matchup_grade_adj: this
# team's own OffAdj z-score vs the opponent's DefAdj z-score. ONLY
# meaningful for --season 2026 -- there's no analogous 2025-forward-from-
# 2024 file, so applying this to the 2025 backtest would be nonsensical
# (using a 2026 adjustment to "adjust" games that already happened).
# UNVALIDATED: 2026 has no played games yet to backtest against; this
# strength is a placeholder, not a tuned value like the others in this
# file. Revisit once real 2026 week-1 results exist, the same way every
# other constant here got tuned against 2025.
TARP_ADJ_STRENGTH = 0.15

# Minimum prior-year volume to project a player at all (filters noise).
MIN_PRIOR_VOLUME = dict(pass_att=100, rush_att=30, targets=20)

# Edge thresholds for flagging (in the stat's own units).
EDGE_FLAG = dict(pass_yds=20, rush_yds=12, rec_yds=12,
                 pass_att=3, rush_att=3, receptions=1.0)
